[2025-04-07T16:11:05.238+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dlt_citibike_pipeline.upload_new_data_02 scheduled__2025-03-01T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
