[2025-04-05T15:14:13.570+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-05T15:14:13.735+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dlt_ingestion_dag.run_dlt_ingestion manual__2025-04-05T15:14:07.705247+00:00 [queued]>
[2025-04-05T15:14:13.747+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dlt_ingestion_dag.run_dlt_ingestion manual__2025-04-05T15:14:07.705247+00:00 [queued]>
[2025-04-05T15:14:13.747+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-05T15:14:13.767+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_dlt_ingestion> on 2025-04-05 15:14:07.705247+00:00
[2025-04-05T15:14:13.778+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=663) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-05T15:14:13.779+0000] {standard_task_runner.py:72} INFO - Started process 665 to run task
[2025-04-05T15:14:13.780+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dlt_ingestion_dag', 'run_dlt_ingestion', 'manual__2025-04-05T15:14:07.705247+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dlt_ingestion_dag.py', '--cfg-path', '/tmp/tmpzxuvu_s6']
[2025-04-05T15:14:13.782+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask run_dlt_ingestion
[2025-04-05T15:14:13.846+0000] {task_command.py:467} INFO - Running <TaskInstance: dlt_ingestion_dag.run_dlt_ingestion manual__2025-04-05T15:14:07.705247+00:00 [running]> on host f244989754ae
[2025-04-05T15:14:13.952+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dlt_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_dlt_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T15:14:07.705247+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-05T15:14:07.705247+00:00'
[2025-04-05T15:14:13.954+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-05T15:14:13.954+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-05T15:14:13.954+0000] {logging_mixin.py:190} INFO - Current task name:run_dlt_ingestion state:running start_date:2025-04-05 15:14:13.735831+00:00
[2025-04-05T15:14:13.955+0000] {logging_mixin.py:190} INFO - Dag name:dlt_ingestion_dag and current dag run status:running
[2025-04-05T15:14:13.955+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-05T15:14:19.482+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dlt_ingestion_dag.py", line 21, in run_dlt_script
    subprocess.run(["python", "/opt/airflow/dlt_pipeline/dlt_citibike.py"], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 573, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/opt/airflow/dlt_pipeline/dlt_citibike.py']' returned non-zero exit status 1.
[2025-04-05T15:14:19.511+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-05T15:14:19.513+0000] {logging_mixin.py:190} INFO - Task start:2025-04-05 15:14:13.735831+00:00 end:2025-04-05 15:14:19.510624+00:00 duration:5.774793
[2025-04-05T15:14:19.513+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): run_dlt_ingestion> dag:<DAG: dlt_ingestion_dag> dagrun:<DagRun dlt_ingestion_dag @ 2025-04-05 15:14:07.705247+00:00: manual__2025-04-05T15:14:07.705247+00:00, state:running, queued_at: 2025-04-05 15:14:07.732358+00:00. externally triggered: True>
[2025-04-05T15:14:19.514+0000] {logging_mixin.py:190} INFO - Failure caused by Command '['python', '/opt/***/dlt_pipeline/dlt_citibike.py']' returned non-zero exit status 1.
[2025-04-05T15:14:19.515+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=dlt_ingestion_dag, task_id=run_dlt_ingestion, run_id=manual__2025-04-05T15:14:07.705247+00:00, execution_date=20250405T151407, start_date=20250405T151413, end_date=20250405T151419
[2025-04-05T15:14:19.582+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-05T15:14:19.583+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task run_dlt_ingestion (Command '['python', '/opt/airflow/dlt_pipeline/dlt_citibike.py']' returned non-zero exit status 1.; 665)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dlt_ingestion_dag.py", line 21, in run_dlt_script
    subprocess.run(["python", "/opt/airflow/dlt_pipeline/dlt_citibike.py"], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 573, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/opt/airflow/dlt_pipeline/dlt_citibike.py']' returned non-zero exit status 1.
[2025-04-05T15:14:19.641+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-05T15:14:19.680+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T15:14:19.682+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
